MEN - Z72 MDIS Driver - Z72 MDIS Driver: z72_drv.c File Reference
Z72 MDIS Driver
Z72 MDIS Driver: z72_drv.c File Reference
z72_drv.c File Reference
Low-level driver for Z72_OWB module.
Functions
static int32 Z72_Init (DESC_SPEC *descP, OSS_HANDLE *osHdl, MACCESS *ma, OSS_SEM_HANDLE *devSemHdl, OSS_IRQ_HANDLE *irqHdl, LL_HANDLE **llHdlP)
Allocate and return low-level handle, initialize hardware.
static int32 Z72_Exit (LL_HANDLE **llHdlP)
De-initialize hardware and clean up memory.
static int32 Z72_Read (LL_HANDLE *llHdl, int32 ch, int32 *valueP)
Read a value from the device, not supported by this driver!
static int32 Z72_Write (LL_HANDLE *llHdl, int32 ch, int32 value)
Write a value to the device, not supported by this driver!
static int32 Z72_SetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64)
Set the driver status.
static int32 Z72_GetStat (LL_HANDLE *llHdl, int32 code, int32 ch, INT32_OR_64 *value32_or_64P)
Get the driver status.
static int32 Z72_BlockRead (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrRdBytesP)
Read a data block from the device, not supported by this driver!
static int32 Z72_BlockWrite (LL_HANDLE *llHdl, int32 ch, void *buf, int32 size, int32 *nbrWrBytesP)
Write a data block from the device, not supported by this driver!
static int32 Z72_Irq (LL_HANDLE *llHdl)
Interrupt service routine.
static int32 Z72_Info (int32 infoType,...)
Get information about hardware and driver requirements.
static char * Ident (void)
Return ident string.
static int32 Cleanup (LL_HANDLE *llHdl, int32 retCode)
Close all handles, free memory and return error code.
static int32 readRom (LL_HANDLE *llHdl, u_int8 *buf, u_int32 numBytes)
Read content of OWB devices ROM.
static int32 skipRom (LL_HANDLE *llHdl)
Send skip ROM command to OWB device.
static int32 readMemory (LL_HANDLE *llHdl, u_int32 majState, u_int8 *buf, u_int16 size, u_int16 offs)
Read content of OWB devices memory or status region.
static int32 masterTxReset (LL_HANDLE *llHdl)
Perform a Reset/Presence Pulse Cycle on the OWBus.
static int32 waitOnReady (LL_HANDLE *llHdl)
wait for started command to finish
static int32 getDevError (LL_HANDLE *llHdl)
Parse saved status for errors.
static int32 execCmd (LL_HANDLE *llHdl, u_int8 *data, u_int32 cmd)
Execute specified command.
static void byteCrc (u_int8 *crc, u_int8 c)
compute CRC8 for passed byte based on old CRC value
static void byteCrcFinish (u_int8 *crc)
finsh crc computation and reflect crc for comparing
static u_int8 bufCrc8 (u_int8 crcStart, u_int8 *buf, u_int32 len)
compute CRC on specified buffer
void Z72_GetEntry (LL_ENTRY *drvP)
Initialize driver's jump table.
static u_int8 reflectByte (u_int8 c)
reflect byte specified (MSB <---> LSB)
Detailed Description
Low-level driver for Z72_OWB module.
Author:
cs
Date
2010/03/12 14:20:32
Revision
1.3
Required: OSS, DESC, DBG, ID libraries
Preprocessor Switches:
_ONE_NAMESPACE_PER_DRIVER_
Function Documentation
static u_int8 bufCrc8 (u_int8 crcStart, u_int8 * buf, u_int32 len) [static]
compute CRC on specified buffer
Parameters:
crcStart IN Init value for CRC
buf IN buffer with data
len IN number of bytes to consider from buf
Returns:
computed crc
References byteCrc(), and byteCrcFinish().
Referenced by readRom().
static void byteCrc (u_int8 * crc, u_int8 c) [static]
compute CRC8 for passed byte based on old CRC value
Parameters:
crc IN/OUT buffer with old/new CRC value
c IN character to be added to crc
References reflectByte(), Z72_OWB_ROMCRC_HIGHBIT, and Z72_OWB_ROMCRC_POLY.
Referenced by bufCrc8(), and readMemory().
static void byteCrcFinish (u_int8 * crc) [static]
finsh crc computation and reflect crc for comparing
Parameters:
crc IN/OUT buffer with old/new CRC value
References reflectByte(), Z72_OWB_ROMCRC_HIGHBIT, Z72_OWB_ROMCRC_ORDER, and Z72_OWB_ROMCRC_POLY.
Referenced by bufCrc8(), and readMemory().
static int32 Cleanup (LL_HANDLE * llHdl, int32 retCode) [static]
Close all handles, free memory and return error code.
Warning:
The low-level handle is invalid after this function is called.
Parameters:
llHdl IN Low-level handle
retCode IN Return value
Returns:
IN retCode
References DBH, LL_HANDLE::descHdl, LL_HANDLE::exeSem, LL_HANDLE::memAlloc, and LL_HANDLE::osHdl.
Referenced by Z72_Exit(), and Z72_Init().
static int32 execCmd (LL_HANDLE * llHdl, u_int8 * data, u_int32 cmd) [static]
Execute specified command.
Parameters:
llHdl IN Low-level handle
data OUT buffer for data read or to write
cmd IN command to execute
Returns:
0 On success or error code
References LL_HANDLE::exeStatus, getDevError(), LL_HANDLE::ma, LL_HANDLE::osHdl, waitOnReady(), Z72_CTL_CMD_MASK, Z72_CTL_CMD_RBIT, Z72_CTL_CMD_RBYT, Z72_CTL_CMD_WBIT, Z72_CTL_CMD_WBYT, Z72_CTL_EXEC, Z72_ERR_BUSY, Z72_POLL_TOUT, Z72_REG_CTL, Z72_REG_RD, Z72_REG_STS, Z72_REG_WRT, Z72_RETRY_MAX, and Z72_STS_BUSY.
Referenced by masterTxReset(), readMemory(), readRom(), and skipRom().
static int32 getDevError (LL_HANDLE * llHdl) [static]
Parse saved status for errors.
Parameters:
llHdl IN Low-level handle
Returns:
0 On success or error code detected
References LL_HANDLE::exeStatus, Z72_ERR_NO_DEVICE, Z72_ERR_PGM, Z72_STS_EEXE, Z72_STS_EPP1, Z72_STS_EPP2, and Z72_STS_ERPP.
Referenced by execCmd().
static char * Ident (void) [static]
Return ident string.
Returns:
Pointer to ident string
Referenced by Z72_Init().
static int32 masterTxReset (LL_HANDLE * llHdl) [static]
Perform a Reset/Presence Pulse Cycle on the OWBus.
Parameters:
llHdl IN Low-level handle
Returns:
0 On success or error code
References execCmd(), LL_HANDLE::majState, Z72_CTL_CMD_RPP, and Z72_ST_MAJ_IDLE.
Referenced by readMemory(), readRom(), skipRom(), and Z72_Init().
static int32 readMemory (LL_HANDLE * llHdl, u_int32 majState, u_int8 * buf, u_int16 size, u_int16 offs) [static]
Read content of OWB devices memory or status region.
The function will read the specified amount of bytes from the devices memory or status region. Every received CRC is checked for validity.
Parameters:
llHdl IN Low-level handle
majState IN kind of read to perform
buf OUT buffer for read ROM data
size IN number of bytes to read
offs IN start offset in region to read
Returns:
0 On success or error code
References byteCrc(), byteCrcFinish(), DBH, execCmd(), LL_HANDLE::fncState, LL_HANDLE::majState, masterTxReset(), LL_HANDLE::mode, skipRom(), Z72_CTL_CMD_RBYT, Z72_CTL_CMD_WBYT, Z72_ERR_BEYOND_MEM, Z72_ERR_CRC, Z72_ERR_NO_ROMFKT, Z72_ERR_UNDEF_STATE, Z72_MODE_AUTO_SKIPROM, Z72_OWB_DS2502_MEM_PAGESIZE, Z72_OWB_DS2502_MEM_READ, Z72_OWB_DS2502_MEM_READ_CRC, Z72_OWB_DS2502_MEM_SIZE, Z72_OWB_DS2502_ST_SIZE, Z72_OWB_DS2502_STATUS_READ, Z72_OWB_ROMCRC_INIT, Z72_ST_MAJ_IDLE, Z72_ST_MAJ_IDLE_MEM, Z72_ST_MAJ_MEM_READ, Z72_ST_MAJ_MEM_READ_CRC, Z72_ST_MAJ_STATUS_READ, Z72_ST_RX_CMD, Z72_ST_RX_CRC1, Z72_ST_RX_CRC2, Z72_ST_RX_DATA, and Z72_ST_RX_TA.
Referenced by Z72_GetStat().
static int32 readRom (LL_HANDLE * llHdl, u_int8 * buf, u_int32 numBytes) [static]
Read content of OWB devices ROM.
The function will always read the full content of the ROM in order to be able to check the CRC which is only received at the end.
Parameters:
llHdl IN Low-level handle
buf OUT buffer for read ROM data
numBytes IN number of bytes to read (>= Z72_OWB_ROM_LEN)
Returns:
0 On success or error code
References bufCrc8(), DBH, execCmd(), LL_HANDLE::majState, masterTxReset(), Z72_CTL_CMD_RBYT, Z72_CTL_CMD_WBYT, Z72_ERR_CRC, Z72_OWB_ROM_LEN, Z72_OWB_ROM_READ, Z72_OWB_ROMCRC_INIT, and Z72_ST_MAJ_IDLE_MEM.
Referenced by Z72_GetStat().
static u_int8 reflectByte (u_int8 c) [static]
reflect byte specified (MSB <---> LSB)
Parameters:
c IN byte to reflect
Returns:
reflected byte
Referenced by byteCrc(), and byteCrcFinish().
static int32 skipRom (LL_HANDLE * llHdl) [static]
Send skip ROM command to OWB device.
Parameters:
llHdl IN Low-level handle
Returns:
0 On success or error code
References DBH, execCmd(), LL_HANDLE::majState, masterTxReset(), Z72_CTL_CMD_WBYT, Z72_OWB_ROM_SKIP, and Z72_ST_MAJ_IDLE_MEM.
Referenced by readMemory().
static int32 waitOnReady (LL_HANDLE * llHdl) [static]
wait for started command to finish
Parameters:
llHdl IN Low-level handle
Returns:
0 On success or error code
References DBH, LL_HANDLE::exeSem, LL_HANDLE::exeStatus, LL_HANDLE::ma, LL_HANDLE::mode, LL_HANDLE::osHdl, Z72_MODE_POLL, Z72_POLL_RETRY_MAX, Z72_POLL_TOUT, Z72_REG_CTL, Z72_REG_STS, Z72_SEM_TOUT, Z72_STS_BUSY, Z72_STS_EIRQ, and Z72_STS_MIRQ.
Referenced by execCmd().
static int32 Z72_BlockRead (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrRdBytesP) [static]
Read a data block from the device, not supported by this driver!
Parameters:
llHdl IN Low-level handle
ch IN Current channel
buf IN Data buffer
size IN Data buffer size
nbrRdBytesP OUT Number of read bytes
Returns:
0 On success or error code
References DBH.
Referenced by Z72_GetEntry().
static int32 Z72_BlockWrite (LL_HANDLE * llHdl, int32 ch, void * buf, int32 size, int32 * nbrWrBytesP) [static]
Write a data block from the device, not supported by this driver!
Parameters:
llHdl IN Low-level handle
ch IN Current channel
buf IN Data buffer
size IN Data buffer size
nbrWrBytesP OUT Number of written bytes
Returns:
0 On success or error code
References DBH.
Referenced by Z72_GetEntry().
static int32 Z72_Exit (LL_HANDLE ** llHdlP) [static]
De-initialize hardware and clean up memory.
The function deinitializes the hardware. The interrupt is disabled.
Parameters:
llHdlP IN Pointer to low-level driver handle
Returns:
0 On success or error code
References Cleanup(), DBH, and Z72_SetStat().
Referenced by Z72_GetEntry().
void Z72_GetEntry (LL_ENTRY * drvP)
Initialize driver's jump table.
Parameters:
drvP OUT Pointer to the initialized jump table structure
References Z72_BlockRead(), Z72_BlockWrite(), Z72_Exit(), Z72_GetStat(), Z72_Info(), Z72_Init(), Z72_Irq(), Z72_Read(), Z72_SetStat(), and Z72_Write().
static int32 Z72_GetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 * value32_or_64P) [static]
Get the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h).
Parameters:
llHdl IN Low-level handle
code IN status code
ch IN Current channel
value32_or_64P IN Pointer to block data structure (M_SG_BLOCK) for block status codes
value32_or_64P OUT Data pointer or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns:
0 On success or error code
References CH_NUMBER, LL_HANDLE::dbgLevel, DBH, LL_HANDLE::idFuncTbl, INT32_OR_64, LL_HANDLE::irqCount, readMemory(), readRom(), Z72_BLK_MEM, Z72_BLK_MEM_CRC, Z72_BLK_ROM_READ, Z72_BLK_STATUS, Z72_OWB_ROM_LEN, Z72_ST_MAJ_MEM_READ, Z72_ST_MAJ_MEM_READ_CRC, and Z72_ST_MAJ_STATUS_READ.
Referenced by Z72_GetEntry().
static int32 Z72_Info (int32 infoType, ...) [static]
Get information about hardware and driver requirements.
The following info codes are supported:
  Code                      Description
  ------------------------  -----------------------------
  LL_INFO_HW_CHARACTER      Hardware characteristics
  LL_INFO_ADDRSPACE_COUNT   Number of required address spaces
  LL_INFO_ADDRSPACE         Address space information
  LL_INFO_IRQ               Interrupt required
  LL_INFO_LOCKMODE          Process lock mode required
The LL_INFO_HW_CHARACTER code returns all address and data modes (ORed) which are supported by the hardware (MDIS_MAxx, MDIS_MDxx).
The LL_INFO_ADDRSPACE_COUNT code returns the number of address spaces used by the driver.
The LL_INFO_ADDRSPACE code returns information about one specific address space (MDIS_MAxx, MDIS_MDxx). The returned data mode represents the widest hardware access used by the driver.
The LL_INFO_IRQ code returns whether the driver supports an interrupt routine (TRUE or FALSE).
The LL_INFO_LOCKMODE code returns which process locking mode the driver needs (LL_LOCK_xxx).
Parameters:
infoType IN Info code
... IN Argument(s)
Returns:
0 On success or error code
References ADDRSPACE_COUNT, ADDRSPACE_SIZE, and USE_IRQ.
Referenced by Z72_GetEntry().
static int32 Z72_Init (DESC_SPEC * descP, OSS_HANDLE * osHdl, MACCESS * ma, OSS_SEM_HANDLE * devSemHdl, OSS_IRQ_HANDLE * irqHdl, LL_HANDLE ** llHdlP) [static]
Allocate and return low-level handle, initialize hardware.
The function initializes all channels with the definitions made in the descriptor. The interrupt is disabled.
The function decodes these descriptor entries in addition to the general descriptor keys.
Parameters:
descP IN Pointer to descriptor data
osHdl IN OSS handle
ma IN HW access handle
devSemHdl IN Device semaphore handle
irqHdl IN IRQ handle
llHdlP OUT Pointer to low-level driver handle
Returns:
0 On success or error code
References Cleanup(), DBH, Ident(), masterTxReset(), Z72_MODE_AUTO_SKIPROM, Z72_MODE_POLL, and Z72_SetStat().
Referenced by Z72_GetEntry().
static int32 Z72_Irq (LL_HANDLE * llHdl) [static]
Interrupt service routine.
The interrupt is triggered when ??? occurs.
If the driver can detect the interrupt's cause it returns LL_IRQ_DEVICE or LL_IRQ_DEV_NOT, otherwise LL_IRQ_UNKNOWN.
Parameters:
llHdl IN Low-level handle
Returns:
LL_IRQ_DEVICE IRQ caused by device LL_IRQ_DEV_NOT IRQ not caused by device LL_IRQ_UNKNOWN Unknown
References DBH, LL_HANDLE::exeSem, LL_HANDLE::exeStatus, LL_HANDLE::irqCount, LL_HANDLE::ma, LL_HANDLE::osHdl, Z72_REG_STS, Z72_STS_EIRQ, and Z72_STS_MIRQ.
Referenced by Z72_GetEntry().
static int32 Z72_Read (LL_HANDLE * llHdl, int32 ch, int32 * valueP) [static]
Read a value from the device, not supported by this driver!
Parameters:
llHdl IN Low-level handle
ch IN Current channel
valueP OUT Read value
Returns:
0 On success or error code
References DBH.
Referenced by Z72_GetEntry().
static int32 Z72_SetStat (LL_HANDLE * llHdl, int32 code, int32 ch, INT32_OR_64 value32_or_64) [static]
Set the driver status.
The driver supports these status codes in addition to the standard codes (see mdis_api.h).
Parameters:
llHdl IN Low-level handle
code IN status code
ch IN Current channel
value32_or_64 IN Data or pointer to block data structure (M_SG_BLOCK) for block status codes
Returns:
0 On success or error code
References LL_HANDLE::dbgLevel, DBH, LL_HANDLE::irqCount, LL_HANDLE::ma, LL_HANDLE::mode, Z72_CTL_EIRQ, Z72_CTL_MIRQ, Z72_MODE_AUTO_SKIPROM, Z72_MODE_POLL, Z72_REG_CTL, Z72_REG_STS, Z72_ROM_SKIP_AUTOEN, Z72_STS_EIRQ, and Z72_STS_MIRQ.
Referenced by Z72_Exit(), Z72_GetEntry(), and Z72_Init().
static int32 Z72_Write (LL_HANDLE * llHdl, int32 ch, int32 value) [static]
Write a value to the device, not supported by this driver!
Parameters:
llHdl IN Low-level handle
ch IN Current channel
value IN Read value
Returns:
0 on success or error code
References DBH.
Referenced by Z72_GetEntry().